name: Publish package on NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Getting repository data
      - uses: actions/checkout@v2
      - name: Install dependencies and NPM Publish
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn ci
      - run: yarn build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
